# Generated by Django 5.0.7 on 2024-07-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posted_by',
        ),
    ]
