# Generated by Django 5.0.7 on 2024-07-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_comment_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='momi', max_length=100),
            preserve_default=False,
        ),
    ]
